# Generated by Django 4.0.3 on 2022-03-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='plublish',
            new_name='publish',
        ),
    ]
